<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="19355" started-at="2017-05-14T14:40:52Z" finished-at="2017-05-14T14:41:12Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="19355" started-at="2017-05-14T14:40:52Z" finished-at="2017-05-14T14:41:12Z">
      <class name="com.test.m2test.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="beforeTest" is-config="true" duration-ms="2858" started-at="2017-05-14T22:40:52Z" finished-at="2017-05-14T22:40:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="beforeClass" is-config="true" duration-ms="0" started-at="2017-05-14T22:40:55Z" finished-at="2017-05-14T22:40:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="beforeMethod" is-config="true" duration-ms="1173" started-at="2017-05-14T22:40:55Z" finished-at="2017-05-14T22:40:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f(java.lang.Integer, java.lang.String)[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="f" duration-ms="1260" started-at="2017-05-14T22:40:56Z" data-provider="dp" finished-at="2017-05-14T22:40:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[a]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [网页] but found [AcFun弹幕视频网 - 认真你就输啦 (・ω・)ノ- ( ゜- ゜)...官网
AcFun是一家弹幕视频网站,致力于为每一个人带来欢乐。... UP: 萝菽菽164511:506中国交通事故合集20170509:每天10分钟最新国内车祸实例,助你提高安全意识UP: 交通事故...
www.acfun.cn/  - 百度快照 - 396条评价
AcFun娱乐区
包含了当下最新,最欢乐的各类搞笑视频,及洗脑的鬼畜作品和各种综艺节目
AcFun番剧区
国内外优秀动漫视频,实时更新连载番剧的宅文化圣地!今天,你补番了吗?]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [网页] but found [AcFun弹幕视频网 - 认真你就输啦 (・ω・)ノ- ( ゜- ゜)...官网
AcFun是一家弹幕视频网站,致力于为每一个人带来欢乐。... UP: 萝菽菽164511:506中国交通事故合集20170509:每天10分钟最新国内车祸实例,助你提高安全意识UP: 交通事故...
www.acfun.cn/  - 百度快照 - 396条评价
AcFun娱乐区
包含了当下最新,最欢乐的各类搞笑视频,及洗脑的鬼畜作品和各种综艺节目
AcFun番剧区
国内外优秀动漫视频,实时更新连载番剧的宅文化圣地!今天,你补番了吗?]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.m2test.NewTest.f(NewTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-05-14T22:41:02Z" finished-at="2017-05-14T22:41:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="beforeMethod" is-config="true" duration-ms="437" started-at="2017-05-14T22:41:02Z" finished-at="2017-05-14T22:41:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f(java.lang.Integer, java.lang.String)[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="f" duration-ms="3256" started-at="2017-05-14T22:41:03Z" data-provider="dp" finished-at="2017-05-14T22:41:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[b]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [网页] but found [哔哩哔哩 (゜-゜)つロ 干杯~-bilibili官网
bilibili是国内知名的视频弹幕网站,这里有最及时的动漫新番,最棒的ACG氛围,最有创意的Up主。大家可以在这里找到许多欢乐。
www.bilibili.com/  - 百度快照 - 2594条评价
国产动画时刻表
哔哩哔哩 正版国漫新番连载 每日更新 带给你最愉悦的观看享受
新番动画时刻表
哔哩哔哩 为你提供每日最新连载动画 最好看的新番
游戏视频
热门游戏视频抢先看 高手达人游戏攻略分享 国内最欢乐的游戏视频分享社区
纪录片
哔哩哔哩 提供海内外优质的记录片 海量资源 在线观看
哔哩哔哩手机客户端
使用客户端 高清更流畅，缓存省流量！还不快来试一试
哔哩哔哩直播
bilibili 直播让您拉进与小伙伴们之间的距离]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [网页] but found [哔哩哔哩 (゜-゜)つロ 干杯~-bilibili官网
bilibili是国内知名的视频弹幕网站,这里有最及时的动漫新番,最棒的ACG氛围,最有创意的Up主。大家可以在这里找到许多欢乐。
www.bilibili.com/  - 百度快照 - 2594条评价
国产动画时刻表
哔哩哔哩 正版国漫新番连载 每日更新 带给你最愉悦的观看享受
新番动画时刻表
哔哩哔哩 为你提供每日最新连载动画 最好看的新番
游戏视频
热门游戏视频抢先看 高手达人游戏攻略分享 国内最欢乐的游戏视频分享社区
纪录片
哔哩哔哩 提供海内外优质的记录片 海量资源 在线观看
哔哩哔哩手机客户端
使用客户端 高清更流畅，缓存省流量！还不快来试一试
哔哩哔哩直播
bilibili 直播让您拉进与小伙伴们之间的距离]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.m2test.NewTest.f(NewTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-05-14T22:41:11Z" finished-at="2017-05-14T22:41:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-05-14T22:41:11Z" finished-at="2017-05-14T22:41:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.test.m2test.NewTest@53b32d7]" name="afterTest" is-config="true" duration-ms="390" started-at="2017-05-14T22:41:11Z" finished-at="2017-05-14T22:41:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.test.m2test.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
